### ISSUE TITLE
Position Summary and Hours Breakdown/Total Time Do not add up

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#278] opened 2019-09-27 22:51 UTC
Position Summary hours total does not always match Hours Breakdown, Total Time, or Total Time Counted Towards Appreciations (the last three of which seem to be consistent with each other).

In my clubhouse, the Position Summary total is 188:59, but my Total Hours, and the total of Hours Breakdown is 189:01. That shouldn't happen.

**Comment by mikeburg** [comment] 2022-03-26 03:58
This is a bug, yet not a bug. All timesheet durations are stored in seconds yet displayed in hours & minutes, this includes the Total Hours. The later count is the sum of all entries' duration. Some mismatch will appear to happen with a large count of timesheet entries. Welcome to the world of rounding!

Closing this out since it's not a critical issue.

**Closed by mikeburg** 2022-03-26 03:58 UTC
Labels: Bug, Bite Sized
